{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import requests\n",
    "import json\n",
    "import os\n",
    "from datetime import datetime\n",
    "import time\n",
    "import pandas as pd\n",
    "\n",
    "class EdgarFetcher:\n",
    "    \"\"\"\n",
    "    Professional EDGAR API client for fetching SEC documents\n",
    "    Demonstrates proper enterprise data handling\n",
    "    \"\"\"\n",
    "    \n",
    "    def __init__(self, user_agent=\"your-company your-email\"):\n",
    "        self.base_url = \"https://data.sec.gov\"\n",
    "        self.headers = {\n",
    "            \"User-Agent\": user_agent,  # SEC requires identification\n",
    "            \"Accept-Encoding\": \"gzip, deflate\",\n",
    "            \"Host\": \"data.sec.gov\"\n",
    "        }\n",
    "        self.rate_limit_delay = 0.1  # SEC allows 10 requests/second\n",
    "    \n",
    "    def get_company_facts(self, cik):\n",
    "        \"\"\"Get company facts (CIK lookup)\"\"\"\n",
    "        url = f\"{self.base_url}/api/xbrl/companyfacts/CIK{cik:010d}.json\"\n",
    "        \n",
    "        try:\n",
    "            response = requests.get(url, headers=self.headers)\n",
    "            response.raise_for_status()\n",
    "            time.sleep(self.rate_limit_delay)\n",
    "            return response.json()\n",
    "        except requests.exceptions.RequestException as e:\n",
    "            print(f\"Error fetching company facts: {e}\")\n",
    "            return None\n",
    "    \n",
    "    def search_filings(self, cik, form_type=\"10-K\", count=5):\n",
    "        \"\"\"Search for specific form types\"\"\"\n",
    "        url = f\"{self.base_url}/api/xbrl/submissions/CIK{cik:010d}.json\"\n",
    "        \n",
    "        try:\n",
    "            response = requests.get(url, headers=self.headers)\n",
    "            response.raise_for_status()\n",
    "            data = response.json()\n",
    "            \n",
    "            # Extract recent filings\n",
    "            filings = data.get('filings', {}).get('recent', {})\n",
    "            \n",
    "            # Filter for specific form type\n",
    "            form_data = []\n",
    "            for i, form in enumerate(filings.get('form', [])):\n",
    "                if form == form_type and len(form_data) < count:\n",
    "                    form_data.append({\n",
    "                        'form': form,\n",
    "                        'filingDate': filings['filingDate'][i],\n",
    "                        'accessionNumber': filings['accessionNumber'][i],\n",
    "                        'primaryDocument': filings['primaryDocument'][i],\n",
    "                        'reportDate': filings['reportDate'][i]\n",
    "                    })\n",
    "            \n",
    "            time.sleep(self.rate_limit_delay)\n",
    "            return form_data\n",
    "            \n",
    "        except requests.exceptions.RequestException as e:\n",
    "            print(f\"Error searching filings: {e}\")\n",
    "            return []\n",
    "    \n",
    "    def download_filing(self, accession_number, primary_document, save_path):\n",
    "        \"\"\"Download the actual filing document\"\"\"\n",
    "        # Remove dashes from accession number for URL\n",
    "        accession_clean = accession_number.replace('-', '')\n",
    "        \n",
    "        # Construct document URL\n",
    "        url = f\"{self.base_url}/Archives/edgar/data/{accession_clean}/{primary_document}\"\n",
    "        \n",
    "        try:\n",
    "            response = requests.get(url, headers=self.headers)\n",
    "            response.raise_for_status()\n",
    "            \n",
    "            # Save the document\n",
    "            os.makedirs(os.path.dirname(save_path), exist_ok=True)\n",
    "            with open(save_path, 'wb') as f:\n",
    "                f.write(response.content)\n",
    "            \n",
    "            print(f\"Downloaded: {save_path}\")\n",
    "            time.sleep(self.rate_limit_delay)\n",
    "            return True\n",
    "            \n",
    "        except requests.exceptions.RequestException as e:\n",
    "            print(f\"Error downloading filing: {e}\")\n",
    "            return False\n",
    "\n",
    "# Company CIK numbers (Central Index Key)\n",
    "COMPANY_CIKS = {\n",
    "    'tesla': 1318605,\n",
    "    'netflix': 1065280,\n",
    "    'amazon': 1018724,\n",
    "    'apple': 320193,\n",
    "    'microsoft': 789019,\n",
    "    'google': 1652044\n",
    "}\n",
    "\n",
    "def setup_demo_documents():\n",
    "    \"\"\"\n",
    "    Download documents for RAG failure demonstration\n",
    "    This creates our realistic enterprise document corpus\n",
    "    \"\"\"\n",
    "    fetcher = EdgarFetcher(\"RAG-Demo-System contact@yourcompany.com\")\n",
    "    \n",
    "    # Create documents directory structure\n",
    "    docs_dir = \"trust_framework/documents\"\n",
    "    os.makedirs(f\"{docs_dir}/tesla\", exist_ok=True)\n",
    "    os.makedirs(f\"{docs_dir}/netflix\", exist_ok=True)\n",
    "    os.makedirs(f\"{docs_dir}/metadata\", exist_ok=True)\n",
    "    \n",
    "    document_registry = []\n",
    "    \n",
    "    print(\"🔍 Fetching Tesla documents...\")\n",
    "    tesla_filings = fetcher.search_filings(COMPANY_CIKS['tesla'], \"10-K\", 2)\n",
    "    \n",
    "    for i, filing in enumerate(tesla_filings):\n",
    "        filename = f\"tesla_10k_{filing['reportDate'][:4]}.html\"\n",
    "        filepath = f\"{docs_dir}/tesla/{filename}\"\n",
    "        \n",
    "        if fetcher.download_filing(\n",
    "            filing['accessionNumber'], \n",
    "            filing['primaryDocument'], \n",
    "            filepath\n",
    "        ):\n",
    "            document_registry.append({\n",
    "                'company': 'tesla',\n",
    "                'document_type': '10-K',\n",
    "                'file_path': filepath,\n",
    "                'report_date': filing['reportDate'],\n",
    "                'filing_date': filing['filingDate'],\n",
    "                'accession_number': filing['accessionNumber'],\n",
    "                'status': 'current' if i == 0 else 'historical'\n",
    "            })\n",
    "    \n",
    "    print(\"🔍 Fetching Netflix documents...\")\n",
    "    netflix_filings = fetcher.search_filings(COMPANY_CIKS['netflix'], \"10-K\", 1)\n",
    "    \n",
    "    for filing in netflix_filings:\n",
    "        filename = f\"netflix_10k_{filing['reportDate'][:4]}.html\"\n",
    "        filepath = f\"{docs_dir}/netflix/{filename}\"\n",
    "        \n",
    "        if fetcher.download_filing(\n",
    "            filing['accessionNumber'], \n",
    "            filing['primaryDocument'], \n",
    "            filepath\n",
    "        ):\n",
    "            document_registry.append({\n",
    "                'company': 'netflix',\n",
    "                'document_type': '10-K',\n",
    "                'file_path': filepath,\n",
    "                'report_date': filing['reportDate'],\n",
    "                'filing_date': filing['filingDate'],\n",
    "                'accession_number': filing['accessionNumber'],\n",
    "                'status': 'current'\n",
    "            })\n",
    "    \n",
    "    # Save document registry\n",
    "    registry_path = f\"{docs_dir}/metadata/document_registry.json\"\n",
    "    with open(registry_path, 'w') as f:\n",
    "        json.dump(document_registry, f, indent=2)\n",
    "    \n",
    "    print(f\"\\n✅ Document setup complete!\")\n",
    "    print(f\"📁 Documents saved to: {docs_dir}/\")\n",
    "    print(f\"📋 Registry saved to: {registry_path}\")\n",
    "    print(f\"📊 Total documents: {len(document_registry)}\")\n",
    "    \n",
    "    return document_registry\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    # Run the setup\n",
    "    documents = setup_demo_documents()\n",
    "    \n",
    "    # Display what we downloaded\n",
    "    df = pd.DataFrame(documents)\n",
    "    print(\"\\n📋 Downloaded Documents:\")\n",
    "    print(df[['company', 'document_type', 'report_date', 'status']].to_string(index=False))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
